spring:
  #SET DB
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.0.20:15432/medieye
    url: jdbc:postgresql://123.142.69.82:15432/medieye
    username: postgresql
    password: dgall0618!
#OAUTH2.0 Profile
  profiles:
    include: oauth
  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: validate
  #Thymeleaf
  thymeleaf:
    enable: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  #GOOGLE
#spring
  security:
    oauth2:
      client:
        registration:
          google:
#            client-id: 820396164812-gukohgoniu1rkmlncvos5ffl8gag6dqe.apps.googleusercontent.com
            client-id: 820396164812-0227ukn7g94e6oc51a64dbevp73gmsdo.apps.googleusercontent.com
            client-secret: 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
#            client-secret: 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
#            redirect-uri: http://localhost:8090/login/oauth2/code/google
            redirect-uri: https://medieye.dgall.synology.me/login/oauth2/code/google
            scope:
            - profile
            - email
  #NAVER
        #registration
          naver:
            client-id: mqerU74izQ9516wy44xV
            client-secret: i4pIDikh8N
#            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            redirect-uri: https://medieye.dgall.synology.me/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
            - name
            - email
            client-name: Naver
  #KAKAO
          kakao:
            client-id: f34a3929f9ab1c6ee31c745ed35aa2d2
            client-secret: M7FCD1qUiPzcyCpFtP0XtzHcDlnNU3kP
            scope:
            - profile_nickname
            - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8090/login/oauth2/code/kakao
            redirect-uri: https://medieye.dgall.synology.me/login/oauth2/code/kakao
            client-authentication-method: POST
      #client
      #Provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#            user-info-authentication-method: header
# Message 
  messages:
    basename: messages
    encoding: UTF-8
    
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  # xml파일 result type에 패키지명을 생략할 수 있도록 alias 설정
  type-aliases-package: kr.co.dgall.medieye_app3.model
  configuration:
    map-underscore-to-camel-case: true

# SERVER PORT
server:
  port: 8090
  tomcat:
    use-relative-redirects: true
